language: python
python:
  - "2.7"
services:
  - postgresql
virtualenv:
  system_site_packages: true
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - gdal-bin
      - python-gdal
env:
  - DATABASE_URL=postgres://postgres:@localhost:5432/wazimap_za
install:
  - pip install -r requirements.txt
script:
  - psql -c 'create database test_wazimap_za;' -U postgres
  - python manage.py migrate
  - "for f in sql/*.sql; do echo $f | psql -U postgres test_wazimap_za; done"
  - python manage.py test --keepdb
