ALTER TABLE accesstointernet RENAME COLUMN "access to internet" TO access_to_internet;
ALTER TABLE agegroupsin5years RENAME COLUMN "age groups in 5 years" TO age_groups_in_5_years;
ALTER TABLE agegroupsin5years_gender RENAME COLUMN "age groups in 5 years" TO age_groups_in_5_years;
ALTER TABLE ageincompletedyears RENAME COLUMN "age in completed years" TO age_in_completed_years;
ALTER TABLE ageincompletedyears_presentschoolattendance RENAME COLUMN "present school attendance" TO present_school_attendance;
ALTER TABLE ageincompletedyears_presentschoolattendance RENAME COLUMN "age in completed years" TO age_in_completed_years;
ALTER TABLE ageincompletedyearssimplified RENAME COLUMN "age in completed years" TO age_in_completed_years;
ALTER TABLE ageofhouseholdhead_genderofhouseholdhead RENAME COLUMN "gender of household head" TO gender_of_household_head;
ALTER TABLE ageofhouseholdhead_genderofhouseholdhead RENAME COLUMN "age of household head" TO age_of_household_head;
ALTER TABLE annualhouseholdincome_genderofhouseholdhead RENAME COLUMN "annual household income" TO annual_household_income;
ALTER TABLE annualhouseholdincome_genderofhouseholdhead RENAME COLUMN "gender of household head" TO gender_of_household_head;
ALTER TABLE annualhouseholdincomeunder18 RENAME COLUMN "annual household income" TO annual_household_income;
ALTER TABLE crimes_accused_age_group RENAME COLUMN "age group" TO age_group;
ALTER TABLE crimes_type_of_crime_year RENAME COLUMN "type of crime" TO type_of_crime;
ALTER TABLE crimes_victims_age_group RENAME COLUMN "age group" TO age_group;
ALTER TABLE ecd_centres_by_registration RENAME COLUMN "registration_incomplete-access_denied" TO registration_incomplete_access_denied;
ALTER TABLE ecd_centres_by_registration RENAME COLUMN "registration_incomplete-closed" TO registration_incomplete_closed;
ALTER TABLE ecd_centres_by_registration RENAME COLUMN "registration_incomplete-not_found" TO registration_incomplete_not_found;
ALTER TABLE electricityforcooking_electricityforheating_electr RENAME COLUMN "electricity for cooking" TO electricity_for_cooking;
ALTER TABLE electricityforcooking_electricityforheating_electr RENAME COLUMN "electricity for heating" TO electricity_for_heating;
ALTER TABLE electricityforcooking_electricityforheating_electr RENAME COLUMN "electricity for lighting" TO electricity_for_lighting;
ALTER TABLE employedindividualannualincome RENAME COLUMN "employed individual annual income" TO employed_individual_annual_income;
ALTER TABLE employedindividualmonthlyincome RENAME COLUMN "employed individual monthly income" TO employed_individual_monthly_income;
ALTER TABLE energyorfuelforcooking RENAME COLUMN "energy or fuel for cooking" TO energy_or_fuel_for_cooking;
ALTER TABLE energyorfuelforheating RENAME COLUMN "energy or fuel for heating" TO energy_or_fuel_for_heating;
ALTER TABLE energyorfuelforlighting RENAME COLUMN "energy or fuel for lighting" TO energy_or_fuel_for_lighting;
ALTER TABLE fatheralive_motheralive RENAME COLUMN "mother alive" TO mother_alive;
ALTER TABLE fatheralive_motheralive RENAME COLUMN "father alive" TO father_alive;
ALTER TABLE gender_maritalstatus RENAME COLUMN "marital status" TO marital_status;
ALTER TABLE gender_populationgroup RENAME COLUMN "population group" TO population_group;
ALTER TABLE genderofheadofhouseholdunder18 RENAME COLUMN "gender of head of household" TO gender_of_head_of_household;
ALTER TABLE highesteducationallevel RENAME COLUMN "highest educational level" TO highest_educational_level;
ALTER TABLE highesteducationallevel17 RENAME COLUMN "highest educational level" TO highest_educational_level;
ALTER TABLE highesteducationallevel20 RENAME COLUMN "highest educational level" TO highest_educational_level;
ALTER TABLE householdgoods RENAME COLUMN "household goods" TO household_goods;
ALTER TABLE individualannualincome15to17 RENAME COLUMN "individual annual income" TO individual_annual_income;
ALTER TABLE individualmonthlyincome15to17 RENAME COLUMN "individual monthly income" TO individual_monthly_income;
ALTER TABLE officialemploymentstatus RENAME COLUMN "official employment status" TO official_employment_status;
ALTER TABLE officialemploymentstatus15to17 RENAME COLUMN "official employment status" TO official_employment_status;
ALTER TABLE population_employment_sector_gender RENAME COLUMN "employment sector" TO employment_sector;
ALTER TABLE population_employment_status_gender RENAME COLUMN "employment status" TO employment_status;
ALTER TABLE populationgroup RENAME COLUMN "population group" TO population_group;
ALTER TABLE provinceofbirth RENAME COLUMN "province of birth" TO province_of_birth;
ALTER TABLE refusedisposal RENAME COLUMN "refuse disposal" TO refuse_disposal;
ALTER TABLE regionofbirth RENAME COLUMN "region of birth" TO region_of_birth;
ALTER TABLE sourceofwater RENAME COLUMN "source of water" TO source_of_water;
ALTER TABLE tenurestatus RENAME COLUMN "tenure status" TO tenure_status;
ALTER TABLE toiletfacilities RENAME COLUMN "toilet facilities" TO toilet_facilities;
ALTER TABLE typeofdwelling RENAME COLUMN "type of dwelling" TO type_of_dwelling;
ALTER TABLE typeofmaindwellingunder18 RENAME COLUMN "type of main dwelling" TO type_of_main_dwelling;
ALTER TABLE typeofsector RENAME COLUMN "type of sector" TO type_of_sector;
ALTER TABLE womenagegroupsin5years15to44 RENAME COLUMN "age groups in 5 years" TO age_groups_in_5_years;
ALTER TABLE youth_access_to_internet_gender RENAME COLUMN "access to internet" TO access_to_internet;
ALTER TABLE youth_accused_offence_type RENAME COLUMN "type of offence" TO type_of_offence;
ALTER TABLE youth_accused_population_group RENAME COLUMN "population group" TO population_group;
ALTER TABLE youth_age_16_to_17_gender_completed_grade9 RENAME COLUMN "completed grade9" TO completed_grade9;
ALTER TABLE youth_age_20_to_24_gender_education_level RENAME COLUMN "education level" TO education_level;
ALTER TABLE youth_age_groups_in_10_years RENAME COLUMN "age groups in 10 years" TO age_groups_in_10_years;
ALTER TABLE youth_causes_of_death_female RENAME COLUMN "cause of death" TO cause_of_death;
ALTER TABLE youth_causes_of_death_male RENAME COLUMN "cause of death" TO cause_of_death;
ALTER TABLE youth_difficulty_functioning RENAME COLUMN "function type" TO function_type;
ALTER TABLE youth_education_attendance_gender_age_incompleted_years RENAME COLUMN "age in completed years" TO age_in_completed_years;
ALTER TABLE youth_electricity_access_gender RENAME COLUMN "electricity access" TO electricity_access;
ALTER TABLE youth_employment_education_training_gender RENAME COLUMN "employment education training" TO employment_education_training;
ALTER TABLE youth_employment_sector_gender RENAME COLUMN "employment sector" TO employment_sector;
ALTER TABLE youth_employment_status_gender RENAME COLUMN "employment status" TO employment_status;
ALTER TABLE youth_female_given_birth RENAME COLUMN "given birth" TO given_birth;
ALTER TABLE youth_female_given_birth_age_in_completed_years RENAME COLUMN "given birth" TO given_birth;
ALTER TABLE youth_female_given_birth_age_in_completed_years RENAME COLUMN "age in completed years" TO age_in_completed_years;
ALTER TABLE youth_gender_population_group RENAME COLUMN "population group" TO population_group;
ALTER TABLE youth_household_crowded_gender RENAME COLUMN "household crowded" TO household_crowded;
ALTER TABLE youth_household_employment RENAME COLUMN "household employment" TO household_employment;
ALTER TABLE youth_income_poverty_age_group RENAME COLUMN "income poverty" TO income_poverty;
ALTER TABLE youth_income_poverty_age_group RENAME COLUMN "age group" TO age_group;
ALTER TABLE youth_income_poverty_gender_population_group RENAME COLUMN "population group" TO population_group;
ALTER TABLE youth_income_poverty_gender_population_group RENAME COLUMN "income poverty" TO income_poverty;
ALTER TABLE youth_labour_force_expanded_age_group_gender RENAME COLUMN "employment status" TO employment_status;
ALTER TABLE youth_labour_force_expanded_age_group_gender RENAME COLUMN "age group" TO age_group;
ALTER TABLE youth_labour_force_official_age_group_gender RENAME COLUMN "employment status" TO employment_status;
ALTER TABLE youth_labour_force_official_age_group_gender RENAME COLUMN "age group" TO age_group;
ALTER TABLE youth_living_with_parents_gender RENAME COLUMN "living with parents" TO living_with_parents;
ALTER TABLE youth_multidimensionally_poor_gender_population_group RENAME COLUMN "population group" TO population_group;
ALTER TABLE youth_multidimensionally_poor_gender_population_group RENAME COLUMN "multidimensionally poor" TO multidimensionally_poor;
ALTER TABLE youth_province_of_birth RENAME COLUMN "province of birth" TO province_of_birth;
ALTER TABLE youth_region_of_birth RENAME COLUMN "region of birth" TO region_of_birth;
ALTER TABLE youth_toilet_access_gender RENAME COLUMN "toilet access" TO toilet_access;
ALTER TABLE youth_type_of_area RENAME COLUMN "type of area" TO type_of_area;
ALTER TABLE youth_type_of_dwelling_gender RENAME COLUMN "type of dwelling" TO type_of_dwelling;
ALTER TABLE youth_victims_offence_type RENAME COLUMN "type of offence" TO type_of_offence;
ALTER TABLE youth_victims_population_group RENAME COLUMN "population group" TO population_group;
ALTER TABLE youth_water_access_gender RENAME COLUMN "water access" TO water_access;